project:
  type: website
  output-dir: docs

website:
  title: "ESS330 Lab 10 - Neva Morgan"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    self-contained: true
    df-print: paged

editor: visual

